CREATE TABLE goals (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title TEXT NOT NULL,
    last_logged TIMESTAMP,
    schedule jsonb,
    motivations text[],
    duration INTEGER,
    user_id INTEGER
        REFERENCES users(id) ON DELETE CASCADE NOT NULL
)