CREATE TABLE goals (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id INTEGER
        REFERENCES users(id) ON DELETE CASCADE NOT NULL,
    action_id INTEGER
        REFERENCES actions(id) ON DELETE CASCADE NOT NULL,
    title TEXT NOT NULL,
    last_logged DATE,
    schedule jsonb,
    countdown INTEGER,
    block_sequence INTEGER[]
)