CREATE TABLE conversations (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    date DATE NOT NULL DEFAULT CURRENT_DATE,
    goal_id INTEGER
        REFERENCES goals(id) ON DELETE CASCADE NOT NULL
)


SELECT date_trunc('day', date), rating
    FROM goal_logs
    WHERE date > now()- interval '1 month' 
    ORDER BY 1 ASC;