CREATE TABLE logs (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    log_id TEXT,
    user_id INTEGER
        REFERENCES users(id) ON DELETE CASCADE NOT NULL,
    date DATE NOT NULL DEFAULT now(),
    -- we want one per day
    goal_id INTEGER
        REFERENCES goals(id) ON DELETE CASCADE,
    reminder_id INTEGER
        REFERENCES reminders(id) ON DELETE CASCADE,
    value jsonb
);