CREATE TABLE counts (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id INTEGER
        REFERENCES users(id) ON DELETE CASCADE NOT NULL,
    block_id INTEGER
        REFERENCES blocks(id) ON DELETE CASCADE NOT NULL,
    date DATE NOT NULL DEFAULT now(),
    -- text will hold journal text, encoded with ${<Stamp type={'Count'} value={2} dimension='col-4' />}
    count INTEGER NOT NULL,
    countb INTEGER,
    unit TEXT
)