CREATE TABLE logs (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id INTEGER
        REFERENCES users(id) ON DELETE CASCADE NOT NULL,
    block_id INTEGER
        REFERENCES blocks(id) ON DELETE CASCADE NOT NULL,
    date DATE NOT NULL DEFAULT now(),
    -- we want one per day
    goal_id INTEGER
        REFERENCES goals(id),
    reminder_id INTEGER
        REFERENCES reminders(id),
    value jsonb
);