BEGIN;

TRUNCATE
  users
  RESTART IDENTITY CASCADE;

INSERT INTO users (username, name, password)
VALUES
  ('demo', 'demo', '$2a$12$umpQ/YEwyYulDYC/71.DY.3PI5ghhgQE7hD69o7iOVYj9Ms9Zd6fK'),
  ('jimbo', 'Jimothy Jones', '$2a$12$34aLVL3/JbUtOVKRAXuHEubOvd.3rG9vhFNLe5U2gIrRI.kLi8tHa'),
  ('martwart', 'Martha Stewart', '$2a$12$34aLVL3/JbUtOVKRAXuHEubOvd.3rG9vhFNLe5U2gIrRI.kLi8tHa');



-- Creating actions seeds
INSERT INTO actions (user_id, title)
VALUES
  (1, 'exercise'),
  (1, 'diet'),
  (1, 'skydiving'),
  (1, 'budgeting'),
  (2, 'knitting'),
  (2, 'karate');



-- Creating goals seeds
INSERT INTO goals (user_id, action_id, title, last_logged, schedule, countdown, block_sequence)
VALUES
  (1, 1, 'climbing', new Date(), {"schedule": "MWF"}, 32, [1,2,3]),
  (1, 1, 'swimming', new Date(), null, null, [4,5,6,7]),
  (1, 2, 'eucalyptus', new Date(), {"schedule": "MTuWThF"}, null, [8,9,10];
  


-- Creating reminders seeds
INSERT INTO reminders(user_id, date, title, schedule, block_sequence)
VALUES
  (1, new Date(), 'Groceries', {"schedule": "Su"}, [18, 19, 20, 21]),
  (1, new Date(), 'Go to DMV', {"date": "Aug-22-2019"}, [22, 23, 24, 25, 26]),



-- Creating block seeds
INSERT INTO blocks (user_id, goal_id, reminder_id, date, type, value, dimension)
VALUES
  (1, 1, null, now(), 'weekly', {"days": "MWF"}, 'col-6'),
  (1, 1, null, now(), 'notes', {"text": "Don't forget the climbing gear"}, 'col-3'),
  (1, 1, null, now(), 'yesno', {"yes": "true"}, 'col-2'),
  (1, 2, null, now(), 'text', {"text": "Swimming at the YMCA"}, 'col-12'),
  (1, 2, null, now(), 'checklist', {“checked”: false, “value”: “5 butterfly laps”}, 'col-8'),
  (1, 2, null, now(), 'checklist', {“checked”: false, “value”: “10 freestyle laps”}, 'col-8'),
  (1, 2, null, now(), 'checklist', {“checked”: false, “value”: “5 breaststroke laps”} 'col-8'),
  (1, 3, null, now(), 'weekly', {"days": "MTuWThF"}, 'col-8'),
  (1, 3, null, now(), 'count', {"count": 100, "units": "leaves"}, 'col-4'),
  (1, 3, null, now(), 'clock', {"time": 1439}, 'col-5'),
  (1, null, 1, now(), 'weekly', {"days": "Su"}, 'col-4'),
  (1, null, 1, now(), 'checklist', {"checked": false, "value": "1000 eucalyptus leaves"}, 'col-7'),
  (1, null, 1, now(), 'subtitle', {"text": "get the good stuff from Sprouts"}, 'col-7'),
  (1, null, 1, now(), 'checklist', {"checked": false, "value": "shampoo"}, 'col-7'),
  (1, null, 2, now(), 'date', {"date": "Aug-22-2019"}, 'col-6'),
  (1, null, 2, now(), 'checklist', {"text": "get driver's license"}, 'col-7'),
  (1, null, 2, now(), 'checklist', {"text": "bring 3 pieces of mail (proof of residence)"}, 'col-7'),
  (1, null, 2, now(), 'checklist', {"text": "bring debit card, not credit card"}, 'col-7'),
  (1, null, 2, now(), 'checklist', {"text": "bring passport"}, 'col-7');


CREATE TABLE blocks (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id INTEGER
        REFERENCES users(id) ON DELETE CASCADE NOT NULL,
    goal_id INTEGER
        REFERENCES goals(id) ON DELETE CASCADE,
    reminder_id INTEGER
        REFERENCES reminders(id) ON DELETE CASCADE,    
    date DATE DEFAULT now(),
    type type NOT NULL,
    value jsonb NOT NULL,
    dimension TEXT NOT NULL,
)
COMMIT;
